server {
    listen 8080;
    server_name www.rtpintelligence.com;
    return 301 https://rtpintelligence.com$request_uri;
}

server {
    listen 8080 default_server;
    server_name rtpintelligence.com;

    root /usr/share/nginx/html;
    index index.html;

    error_page 404 /404.html;

    gzip on;
    gzip_types text/css application/javascript image/svg+xml text/plain application/xml;
    gzip_min_length 512;

    location /assets/ {
        add_header Cache-Control "public, max-age=86400";
        try_files $uri =404;
    }

    location / {
        try_files $uri $uri/ =404;
    }
}
